### PR TITLE
Fix parameter names in a documentation.

### PR DESCRIPTION
**Pull request by andreo**

### CODE REVIEW

**Comment by x-cray** [comment]
Oh, I missed that in params list in #16. Please rebase against the latest master.

**Comment by andreo** [comment]
Done

**Comment by msteinert** [comment]
lgtm

**Comment by bradrydzewski** [comment]
LGTM

**Comment by bradrydzewski** [comment]
@andreo would you mind syncing this pull request with master? we are trying out protected branches and it looks like this might be required in order to merge. Thanks!

**Pull request merged**
