### PR TITLE
adding windows 1909

### PR DESCRIPTION
**Pull request by luthermonson**
just copy pasta for 1909, not sure it will work but here we go.

### CODE REVIEW

**Comment by tboerger** [comment]
This won't work as we don't have such worker yet.

**Comment by luthermonson** [comment]
@tboerger bummer.. going to get it sometime?

**Comment by tboerger** [comment]
Waiting for @bradrydzewski to provide them

**Comment by luthermonson** [comment]
oh great, so leaving this up then and we'll see what happens when we get some builders. thanks!

**Comment by cjellick** [comment]
any movement on this?

**Pull request merged**
