### PR TITLE
Update seccomp to 20.10 docker

### PR DESCRIPTION
**Pull request by techknowlogick**
Alpine 3.14 requires update seccomp profile

### CODE REVIEW

**Comment by techknowlogick** [comment]
CI Fail is unrelated, it is due to docker hub rate limits.

**Review by lafriks — APPROVED** [review]

**Comment by 6543** [comment]
I think it CI will need a retry

**Review by tboerger — APPROVED** [review]

**Comment by tphoney** [comment]
closed, and reopened to re-kick the build.

**Comment by techknowlogick** [comment]
I've just kicked off a CI restart, and it passes on all but 3 pipelines. The fails are due to docker hub ratelimiting.

The pipelines for the dockerfiles I changed passed.

**Comment by 6543** [comment]
merge?

**Comment by tphoney** [comment]
we are looking into solving, hitting the docker rate limiting first. just as a precaution before merging.

**Comment by tphoney** [comment]
thanks for your time and patience @techknowlogick 🎉  merged !! 👍

**Comment by techknowlogick** [comment]
@tphoney thanks much :)

**Comment by bradrydzewski** [comment]
we're getting reports of plugin errors after this was merged https://discourse.drone.io/t/gcr-plugin-issue/9457.  Lets keep an eye on this the next few days.

**Pull request merged**
