### PR TITLE
Allow passing secrets to build args with `build_args_from_env`

### PR DESCRIPTION
**Pull request by rwillians**
Accordingly to what we have discussed recently on gitter, here's my implementation to `build_args_from_env`. The idea is to be able to pass secrets as builds args.

```yml
pipelines
  # ...
  hello-world:
    image: plugins/docker
    repo: octocat/hello-world
    context: src/foo/bar/
    dockerfile: src/foo/bar/Dockerfile
    build_args_from_env:
      - npm_config_registry
      - npm_config_username
      - npm_config_email
      - npm_config__password
    secrets:
      - docker_username
      - docker_password
      - npm_config_registry
      - npm_config_username
      - npm_config_email
      - npm_config__password
    tags:
      - latest
```

### CODE REVIEW

**Comment by rwillians** [comment]
Please note that I had to remove this line https://github.com/drone-plugins/drone-docker/pull/140/files#diff-7ddfb3e035b42cd70649cc33393fe32cL120 to make it work on local development.

```txt
# _/Users/rwillians/Projects/drone-docker
./main.go:120:12: unknown field 'FilePath' in struct literal of type cli.StringSliceFlag
```

**Comment by rwillians** [comment]
@bradrydzewski I've synced with upstream master but whatever change you've made seems to have affected here.

As you can see below, secret's environment variables are no longer been passed as build args.

```txt
sh .drone.sh && \
docker build --rm=true -f docker/Dockerfile -t plugins/docker . --no-cache & \
docker run --rm \
  -e PLUGIN_TAG=latest \
  -e PLUGIN_REPO=octocat/hello-world \
  -e DRONE_COMMIT_SHA=d8dbe4d94f15fe89232e0402c6e8a0ddf21af3ab \
  -e MY_SECRET_FOO=foo \
  -e MY_SECRET_BAR=bar \
  -e PLUGIN_BUILD_ARGS_FROM_ENV=my_secret_foo,my_secret_bar \
  -v $(pwd):$(pwd) \
  -w $(pwd) \
  --privileged \
  plugins/docker --dry-run
+ GOOS=linux
+ GOARCH=amd64
+ CGO_ENABLED=0
+ go build -ldflags '-X main.build=' -a -tags netgo -o release/linux/amd64/drone-docker github.com/drone-plugins/drone-docker/cmd/drone-docker
+ GOOS=linux
+ GOARCH=arm64
+ CGO_ENABLED=0
+ go build -ldflags '-X main.build=' -a -tags netgo -o release/linux/arm64/drone-docker github.com/drone-plugins/drone-docker/cmd/drone-docker
+ GOOS=linux
+ GOARCH=arm
+ CGO_ENABLED=0
+ GOARM=7
+ go build -ldflags '-X main.build=' -a -tags netgo -o release/linux/arm/drone-docker github.com/drone-plugins/drone-docker/cmd/drone-docker
+ GOOS=linux
+ GOARCH=amd64
+ CGO_ENABLED=0
+ go build -a -tags netgo -o release/linux/amd64/drone-docker-heroku github.com/drone-plugins/drone-docker/cmd/drone-docker-heroku
+ GOOS=linux
+ GOARCH=arm64
+ CGO_ENABLED=0
+ go build -a -tags netgo -o release/linux/arm64/drone-docker-heroku github.com/drone-plugins/drone-docker/cmd/drone-docker-heroku
+ GOOS=linux
+ GOARCH=arm
+ CGO_ENABLED=0
+ GOARM=7
+ go build -a -tags netgo -o release/linux/arm/drone-docker-heroku github.com/drone-plugins/drone-docker/cmd/drone-docker-heroku
+ GOOS=linux
+ GOARCH=amd64
+ CGO_ENABLED=0
+ go build -a -tags netgo -o release/linux/amd64/drone-docker-gcr github.com/drone-plugins/drone-docker/cmd/drone-docker-gcr
+ GOOS=linux
+ GOARCH=arm64
+ CGO_ENABLED=0
+ go build -a -tags netgo -o release/linux/arm64/drone-docker-gcr github.com/drone-plugins/drone-docker/cmd/drone-docker-gcr
+ GOOS=linux
+ GOARCH=arm
+ CGO_ENABLED=0
+ GOARM=7
+ go build -a -tags netgo -o release/linux/arm/drone-docker-gcr github.com/drone-plugins/drone-docker/cmd/drone-docker-gcr
[1] 7031
+ /usr/local/bin/dockerd -g /var/lib/docker94MB
Sending build context to Docker daemon  23.55MB
Step 1/3 : FROM docker:17.05.0-ce-dind
 ---> 63b0daf02180
Step 2/3 : ADD release/linux/amd64/drone-docker /bin/
 ---> 9357b9f594c6
Removing intermediate container df8c761a5b11
Step 3/3 : ENTRYPOINT /usr/local/bin/dockerd-entrypoint.sh /bin/drone-docker
 ---> Running in 8bee631e0aec
 ---> 8af50ae168dd
Removing intermediate container 8bee631e0aec
Successfully built 8af50ae168dd
Successfully tagged plugins/docker:latest
[1]  + 7031 done       docker build --rm=true -f docker/Dockerfile -t plugins/docker . --no-cache
Registry credentials not provided. Guest mode enabled.
+ /usr/local/bin/docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 21:43:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 21:43:09 2017
 OS/Arch:      linux/amd64
 Experimental: false
+ /usr/local/bin/docker info
WARNING: bridge-nf-call-iptables is disabled
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.41-moby
Operating System: Alpine Linux v3.5 (containerized)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: a7120ff62ffa
ID: 2PDS:2OOW:O5FD:JSZI:ZHTG:AA4D:FQ3L:IQFN:ZSHZ:S5PA:IL2J:EB4D
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: bridge-nf-call-ip6tables is disabled
+ /usr/local/bin/docker build --rm=true -f Dockerfile -t d8dbe4d94f15fe89232e0402c6e8a0ddf21af3ab . --pull=true --build-arg no_proxy=*.local, 169.254/16 --build-arg NO_PROXY=*.local, 169.254/16 --label org.label-schema.build-date=2017-08-27T22:27:08Z --label org.label-schema.vcs-ref=d8dbe4d94f15fe89232e0402c6e8a0ddf21af3ab --label org.label-schema.vcs-url=
Sending build context to Docker daemon  23.55MB
Step 1/3 : FROM alpine
latest: Pulling from library/alpine
88286f41530e: Pulling fs layer
88286f41530e: Verifying Checksum
88286f41530e: Download complete
88286f41530e: Pull complete
Digest: sha256:1072e499f3f655a032e88542330cf75b02e7bdf673278f701d7ba61629ee3ebe
Status: Downloaded newer image for alpine:latest
 ---> 7328f6f8b418
Step 2/3 : RUN echo hello world
 ---> Running in e61ea1d9d485
hello world
 ---> febae7d33a05
Removing intermediate container e61ea1d9d485
Step 3/3 : LABEL org.label-schema.build-date '2017-08-27T22:27:08Z' org.label-schema.vcs-ref 'd8dbe4d94f15fe89232e0402c6e8a0ddf21af3ab' org.label-schema.vcs-url ''
 ---> Running in 1b6f37893df2
 ---> 5ecec25371eb
Removing intermediate container 1b6f37893df2
[Warning] One or more build-args [NO_PROXY no_proxy] were not consumed
Successfully built 5ecec25371eb
Successfully tagged d8dbe4d94f15fe89232e0402c6e8a0ddf21af3ab:latest
+ /usr/local/bin/docker tag d8dbe4d94f15fe89232e0402c6e8a0ddf21af3ab octocat/hello-world:latest
+ /usr/local/bin/docker rmi d8dbe4d94f15fe89232e0402c6e8a0ddf21af3ab
Untagged: d8dbe4d94f15fe89232e0402c6e8a0ddf21af3ab:latest
+ /usr/local/bin/docker system prune -f
Total reclaimed space: 0B
```

I'll try to take another look during this week but I'm very short on time.

**Comment by bradrydzewski** [comment]
I only changed the directory structure of the project. I did not make any changes to the core codebase that would impact how environment variables are read.

**Comment by bradrydzewski** [comment]
I am not sure what issues you experienced locally, but I applied the below patch and everything worked as expected. I went a head and pushed my changes, so we can just close this.

```diff
index 8d4483e..fb4b04a 100644
--- a/cmd/drone-docker/main.go
+++ b/cmd/drone-docker/main.go
@@ -126,6 +126,11 @@ func main() {
                        Usage:  "build args",
                        EnvVar: "PLUGIN_BUILD_ARGS",
                },
+               cli.StringSliceFlag{
+                       Name:   "args-from-env",
+                       Usage:  "build args",
+                       EnvVar: "PLUGIN_BUILD_ARGS_FROM_ENV",
+               },
                cli.BoolFlag{
                        Name:   "squash",
                        Usage:  "squash the layers at build time",
@@ -195,6 +200,7 @@ func run(c *cli.Context) error {
                        Context:     c.String("context"),
                        Tags:        c.StringSlice("tags"),
                        Args:        c.StringSlice("args"),
+                       ArgsEnv:     c.StringSlice("args-from-env"),
                        Squash:      c.Bool("squash"),
                        Pull:        c.BoolT("pull-image"),
                        Compress:    c.Bool("compress"),
diff --git a/docker.go b/docker.go
index 6f62654..e7ca7e0 100644
--- a/docker.go
+++ b/docker.go
@@ -43,6 +43,7 @@ type (
                Context     string   // Docker build context
                Tags        []string // Docker build tags
                Args        []string // Docker build args
+               ArgsEnv     []string // Docker build args from env
                Squash      bool     // Docker build squash
                Pull        bool     // Docker build pull
                Compress    bool     // Docker build compress
@@ -194,6 +195,9 @@ func commandBuild(build Build) *exec.Cmd {
        if build.Pull {
                args = append(args, "--pull=true")
        }
+       for _, arg := range build.ArgsEnv {
+               addProxyValue(&build, arg)
+       }
        for _, arg := range build.Args {
                args = append(args, "--build-arg", arg)
        }
```

**Comment by rwillians** [comment]
:+1:

**Pull request closed without merging**
