### PR TITLE
fixed appending registry before the repo smart

### PR DESCRIPTION
**Pull request by Zhomart**
It checks for prefix after removing protocols.

### CODE REVIEW

**Comment by tboerger** [comment]
Don't use regenerated, just use net/url :)

**Comment by bradrydzewski** [comment]
could we just document this behavior that when using a custom registry, one should not include `http://` or `https://` in the registry url? I would prefer not to auto-correct invalid input. It can sometimes be more confusing that throwing an exception

**Comment by bradrydzewski** [comment]
so I'd vote for killing this whole block

```diff
-	// this code attempts to normalize the repository name by appending the fully
-	// qualified registry name if otherwise omitted.
-	if p.Login.Registry != defaultRegistry &&
-		!strings.HasPrefix(p.Build.Repo, p.Login.Registry) {
-		p.Build.Repo = p.Login.Registry + "/" + p.Build.Repo
-	}
```

and adding a note to the documentation like this:

Please note that when using a custom registry (other than DockerHub) you will need to provide the registry URL and you will need to use a fully qualified repository name. For example:

```
plugin:
  docker:
    registry: http://registry.company.com
    repo: registry.company.com/my/image
```


... the reason is that when you tag an image locally you have to use `registry.company.com/my/image`. So providing this auto-concatination is inconsistent with how we use Docker locally and seems to cause some confusion. Best to keep it simple and remove the magic, as opposed to add to it.

**Comment by Zhomart** [comment]
It makes sense.

**Pull request closed without merging**
