### PR TITLE
Support reading build-args from a file

### PR DESCRIPTION
**Pull request by mrueg**
Similar to .tags, this allows to set .build-args in a file, allowing to
split configuration (e.g. which image version is used as a base image)
from the Dockerfile.

### CODE REVIEW

**Comment by mrueg** [comment]
@bradrydzewski @tboerger can I request your review here? Thanks!

**Comment by tboerger** [comment]
Since this is one of the most important plugins it should get more approvals.

**Comment by hggh** [comment]
this is a nice idea to support build_args via a file for generating dynamic build_args. Could you @bradrydzewski please have a look?

**Comment by mrueg** [comment]
Closing due to lack of progress.

**Pull request closed without merging**
