### PR TITLE
Add support for s390x architecture

### PR DESCRIPTION
**Pull request by rohitsakala**

### CODE REVIEW

**Comment by tphoney** [comment]
Hi @rohitsakala i want to thankyou for this PR and this feature. Unfortunately we do not have the infrastructure to run this build. So we cannot add this. It would cause a breakage in our current build environment.

Thank you for your understanding.

**Comment by rohitsakala** [comment]
Hello @tphoney ,

I understand the problem. I think I might have a solution. 

IBM provides free access to Z infrastructure for individuals and communities to use.  For individuals, the LinuxONE Community Cloud is available for anyone to get 120 days VM of SLES.  This is great for learning, development, and testing.  For communities, there is the Open Source Software Cloud which is semi-permanent VMs assigned to communities or projects for longer-term access to Z infrastructure.  We can introduce you to the IBM people that manage the Open Source Software Cloud and then work on adding s390x servers to the drone pipeline. 

Does this sound good ? Is this something we can put in your roadmap and work on it?

**Comment by rohitsakala** [comment]
Hello @tphoney ,

is there any update on the proposal ? Thanks 

Pinging @bradrydzewski

**Comment by bradrydzewski** [comment]
> LinuxONE Community Cloud is available for anyone to get 120 days VM of SLES.
> For communities, there is the Open Source Software Cloud which is semi-permanent VMs.

@rohitsakala we need stable, reliable infrastructure before we would consider supporting a new architecture.  I appreciate these suggestions, however, it sounds like they are ephemeral in nature and could terminate or expire, leaving us in a situation where we experience an outage and need to manually intervene (which is a situation we want to avoid).

**Comment by mfriesenegger** [comment]
Hello @bradrydzewski and @tphoney,

You are correct that the LinuxONE Community Cloud (L1CC) is ephemeral in nature but L1CC is not what we are proposing.  The resource is called the Open Source Community Cloud which is a sister resource to L1CC.  The Open Source Community Cloud provides long term, stable and reliable access to the s390x resources that would be dedicated to the drone community. I would connect you with a person at IBM who is responsible.  We would step away so you could discuss your requirements and next steps.  Can we take this conversation to email so that I can make a personal introduction?

**Comment by bradrydzewski** [comment]
Thanks @mfriesenegger for clarifying and offering to make the introduction. You can email me at brad.rydzewski(at)harness.io

**Comment by rohitsakala** [comment]
Hello @bradrydzewski , Hope everything is well. Is it possible for you to give us an update on using IBM s390x servers in your CI. Thanks 😄

**Pull request closed without merging**
