### PR TITLE
Add build secret flag

### PR DESCRIPTION
**Pull request by nashiox**
Add the `secret` flag for build https://github.com/drone-plugins/drone-docker/issues/189

Ex)

```
- name: build
  image: plugins/docker
  volumes:
  - name: secrets
    path: /var/run/secrets
  environment:
    DOCKER_BUILDKIT: 1
  settings:
    repo: my/repos
    secret: id=mysecret,src=/var/run/secrets/mysecret
```

### CODE REVIEW

**Comment by tboerger** [comment]
Does it make sense to provide it as a slice? It's possible to add multiple secrets, right?

**Comment by nashiox** [comment]
Oops, I missed that it was a slice option.
https://github.com/moby/buildkit/blob/master/cmd/buildctl/build.go#L93-L95

Fixed it. 4940a7f73a1c6ddac2f49f32d6c1c433c114a432

**Comment by Weasy666** [comment]
Hi! Is there an ETA when this will land?

**Comment by davezuch** [comment]
Why was this PR closed?

**Comment by tboerger** [comment]
I guess because it haven't been merged within a year.

**Comment by wszychta** [comment]
@tboerger @nashiox It there any chance to reopen this issue? We really need this feature to pass `.netrc` file into Docker build as a temporary secret.

**Pull request closed without merging**
