### PR TITLE
aarch64(arm64) Dockerfile added.

### PR DESCRIPTION
**Pull request by gdeverlant**
To test this plugin inside Drone within arm64 architecture one can use the deployed plugin at https://hub.docker.com/r/ergu/drone-docker-arm64/ and check the related Docker repos at https://hub.docker.com/u/ergu/.

### CODE REVIEW

**Comment by tboerger** [comment]
I don't think that we will build such important images on top of base images that are not official

**Comment by donny-dont** [comment]
I agree with @tboerger here. Maybe it'd be better to replicate that image in here till there's an official dind for arm.

**Comment by gdeverlant** [comment]
I've spend 4 days to try to understand the DinD and how it it working and based my work on already working solution from the official Docker repo.

I tried also run the plugin with privileged mode with the following outpout : 

```
$ docker run --privileged ergu/drone-docker-arm64
+ /usr/local/bin/dockerd -g /var/lib/docker
Registry credentials not provided. Guest mode enabled.
+ /usr/local/bin/docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.8.1
 Git commit:   v17.05.0-ce
 Built:        Tue May 16 11:49:31 2017
 OS/Arch:      linux/arm64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.8.1
 Git commit:   v17.05.0-ce
 Built:        Tue May 16 11:49:31 2017
 OS/Arch:      linux/arm64
 Experimental: false
+ /usr/local/bin/docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.05.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6facb77383876aeff8a6944dde66b3089574
Kernel Version: 4.12.0-gx-117136-g44bd33f
Operating System: Alpine Linux v3.6 (containerized)
OSType: linux
Architecture: aarch64
CPUs: 4
Total Memory: 1.937GiB
Name: 3a78e94dec9e
ID: 336S:H6VX:EDT6:CRXX:AAF7:OUWA:L2UI:LPMB:UES7:QCKM:U3BG:EAZP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
+ /usr/local/bin/docker build --rm=true -f Dockerfile -t 00000000 . --pull=true
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /Dockerfile: no su
h file or directory
time="2017-07-10T18:58:53+09:00" level=fatal msg="exit status 1"
```

If you can prove me that what I did is not working I will agree with your opinion but if it is not the case then you will have to reconsider your position.

**Comment by gdeverlant** [comment]
Well today I tried the plugin on my drone arm64 server and here are the results : 

```
+ /usr/local/bin/dockerd -g /var/lib/docker
Registry credentials not provided. Guest mode enabled.
+ /usr/local/bin/docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.8.1
 Git commit:   v17.05.0-ce
 Built:        Tue May 16 11:49:31 2017
 OS/Arch:      linux/arm64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.8.1
 Git commit:   v17.05.0-ce
 Built:        Tue May 16 11:49:31 2017
 OS/Arch:      linux/arm64
 Experimental: false
+ /usr/local/bin/docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0

0
Server Version: 17.05.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs

 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6facb77383876aeff8a6944dde66b3089574
Kernel Version: 4.12.0-gx-117136-g44bd33f
Operating System: Alpine Linux v3.6 (containerized)
OSType: linux
Architecture: aarch64
CPUs: 4
Total Memory: 1.937GiB
Name: 30fc0363f3a7
ID: YJPV:UDYU:TKFI:JCUD:3F3L:JAFG:ALNJ:NMJB:BAWR:YY7X:EQ7R:7ZTT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:

.0/8
Live Restore Enabled: false

+ /usr/local/bin/docker build --rm=true -f Dockerfile -t d762a0061ce9ad1b8ae9a44ea909eb05783f6a1f . --pull=true
Sending build context to Docker daemon  2.301MB


Step 1/7 : FROM aarch64/alpine
latest: Pulling from aarch64/alpine
e92c575fea6b: Pulling fs layer
e92c575fea6b: Verifying Checksum
e92c575fea6b: Download complete
e92c575fea6b: Pull complete
Digest: sha256:fea6984b3a5b422c41f20a95ff290e77405dd3cb4ff163dd3ad64572e41de0cf
Status: Downloaded newer image for aarch64/alpine:latest
 ---> 8e8812ba3b2d
Step 2/7 : MAINTAINER 
 ---> Running in 907b797f8cae
 ---> 762a18670305
Removing intermediate container 907b797f8cae
Step 3/7 : ENV MONA_VERSION 1.2
 ---> Running in 6e57f73dd87c
 ---> 6118795a2406
Removing intermediate container 6e57f73dd87c
Step 4/7 : COPY MonaServer /srv/MonaServer/
 ---> c4ef394a9c8e
Removing intermediate container 3e099a06e3d6
Step 5/7 : WORKDIR /srv/MonaServer/
 ---> d3c16963dbcd
Removing intermediate container 420a8c817f8b
Step 6/7 : EXPOSE 80 1935 1936 554
 ---> Running in 6e43b6fb4404
 ---> 28e1dbf5ec68
Removing intermediate container 6e43b6fb4404
Step 7/7 : CMD MonaServer --log=7
 ---> Running in 98000161383e
 ---> ae1c85b367c2
Removing intermediate container 98000161383e
Successfully built ae1c85b367c2
Successfully tagged d762a0061ce9ad1b8ae9a44ea909eb05783f6a1f:latest
+ /usr/local/bin/docker tag d762a0061ce9ad1b8ae9a44ea909eb05783f6a1f bambuserver1:5000/ergu/monaserver-arm64:1.2
+ /usr/local/bin/docker push bambuserver1:5000/ergu/monaserver-arm64:1.2
The push refers to a repository [bambuserver1:5000/ergu/monaserver-arm64]
```

But I don't understand why the final result is : 

image

**Comment by tboerger** [comment]
It's not about if it's working now or not. It's about some kind of trust-level. The official images are backed by the company Docker Inc. While your iages are backed "only" by you.

> The problem seems to be the upload... each node of my cluster communicate with my private docker registry via a TLS ca.crt key. Each node has its /etc/docker/certs.d folder set with the TLS ca.crt.

It doesn't matter what the node does, the node is totally independent from this plugin.

**Comment by gdeverlant** [comment]
There is a trust but you don't see it. I've spent 5 days trying to make this thing work. My images are backed by me which based and backed by Docker. I think that me showing you a working plugin should show you that there is trust.

What should I do then for the TLS communication to work ?

**Comment by bradrydzewski** [comment]
First, let me say that I do appreciate the work being done here. With that being said, I do not have the infrastructure to build arm64 images, so even if we merge this, it is not something the core project will be able to use at this time.

Second, I agree that we would not use an unofficial base image. We have companies using drone within regulated environments (ie banks) that would be uncomfortable with this.

I would therefore recommendation working with the Docker team to provide an official aarm64 alpine image. This would not only solve any trust issues, but would be a benefit to the broader Docker community. Once available we can proceed with the pull request.

**Comment by bradrydzewski** [comment]
ok, I did some digging around and found __official__ images for arm
https://github.com/docker-library/official-images#architectures-other-than-amd64

this includes arm images:
https://hub.docker.com/u/arm32v6
https://hub.docker.com/u/arm64v8

so there are, for example, official alpine images:
https://github.com/docker-library/official-images#multiple-architectures

they also seem open to porting new images. let's see if we can get them to include a docker port
https://github.com/docker-library/official-images#architectures-other-than-amd64

**Comment by bradrydzewski** [comment]
we have an official `plugins/docker:linux-arm64` image that can be used now. The official dockerfile will be updated once Docker provides an official `arm64v7/docker:dind` image. I am told they were pending the release of Go 1.9 which is now generally available, so such an image should be available in the near future.

closing in preparation for use of the official image

**Pull request closed without merging**
