### PR TITLE
Update to docker 18.03

### PR DESCRIPTION
**Pull request by sapk**
docker 18.03 fix a bug in multi-stage build : https://github.com/moby/moby/issues/35641

### CODE REVIEW

**Comment by donny-dont** [comment]
@tboerger build is waiting on approval to start.

**Comment by tboerger** [comment]
True, I have approved the build

**Comment by sapk** [comment]
AppVeyor fail seems unrelated.

**Comment by tboerger** [comment]
Appveyor can't build successfully yet.

**Comment by jpds** [comment]
Have a branch for a newer version at #194.

What do we do about appveyor blocking this?

**Comment by appleboy** [comment]
this should be closed.

**Comment by tboerger** [comment]
Yep, we have already updated it differently.

**Pull request closed without merging**
