### PR TITLE
Use the user specified Registry

### PR DESCRIPTION
**Pull request by benwilson512**
Hey! This PR ensures that the ecr executable honors the user specified registry.

The current behavior uses the registry returned by the ECR authentication token regardless of what the user specifies. While this registry is a good default, the token also authenticates the client to push to any other repository that has an AWS trust relationship established with the current account. We should let the user specify one such registry.

### CODE REVIEW

**Comment by benwilson512** [comment]
I was able to get this to build locally, but the docker image I built from the readme got:
```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```
when I changed my drone yaml to the new image. Quite possibly I simply messed up the image build.

**Comment by benwilson512** [comment]
Are the instructions for building in the readme supposed to produce something that can be used in a `.drone.yml` file? I'd like to be able to test this out but I'm unclear on how to do so.

**Comment by bradrydzewski** [comment]
if you use a custom tag (e.g. benwilson512/drone-docker) then you need to register your image with the drone server. Pass `DRONE_ESCALATE=benwilson512/drone-docker` to the Drone server. This will instruct the agent to run the build in privileged mode, allowing docker-in-docker.

**Comment by benwilson512** [comment]
Ah excellent, thanks! Very new to the drone ecosystem still.

**Comment by benwilson512** [comment]
I can confirm that this works.

**Comment by tboerger** [comment]
Appveyor is expected to fail, so imho this is safe to merge.

**Pull request merged**
